### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by wolske** [semoss/semoss#1]
The project name includes the phrase "Open Source" but there is no mention of what license applies to this system.

**Comment by webmaven** [comment]
The homepage mentions the GPL: http://semoss.org/

**Comment by wolske** [comment]
C'mon Mike, you know that's not sufficient.
Unfortunately it looks like the codebase is abandoned.

**Comment by webmaven** [comment]
@wolske, of course I know that.

Anyway, perhaps we should ask @ksmart14, @semoss, or @philipcdavis to fix the licensing situation. Or, you might even create a PR that fixes the issue that one of them would only have to merge...

**Comment by kverma7** [comment]
Hi @wolske and @webmaven - LICENSE file has been committed. Thanks.

**Comment by webmaven** [comment]
Thanks, @kverma7! :tada:
