### ISSUE TITLE
[TASK] Bedrock Engine Streaming 

### ISSUE THREAD

**Issue by kunal0137** [SEMOSS/semoss#109]
### Description 

Bedrock engine streaming is currently broken. Should affect all model types in bedrock, but need to test Titan, Meta, Claude, etc. 

### Existing

Is there any relevant code or ui feature that the developer should know about when resolving this issue. 

### Reference

This issue references. . .

### Tasks

What are more specific tasks that a developer needs to take to consider this issue resolved.

**Comment by yashashah11** [comment]
@mmoore2118 : Can you please confirm if you have started working on this defect. If not, then we are going to fix from ourside i.e. USI team.

**Comment by mmoore2118** [comment]
@yashashah11 Yes I have started working on it should have a merge request up for it by tomorrow
