### ISSUE TITLE
[TASK] Compile of Java can lead to two set of classes

### ISSUE THREAD

**Issue by kunal0137** [SEMOSS/semoss#110]
### Description 

When you update the java folder and recompile java, sometimes two sets of classes appear and they conflict. We can wipe the classes folder prior to compiling to prevent this. 

### Existing

Is there any relevant code or ui feature that the developer should know about when resolving this issue. 

### Reference

This issue references. . .

### Tasks

What are more specific tasks that a developer needs to take to consider this issue resolved.

**Comment by shivanshpatel13** [comment]
Estimated time for completion EOW Sept 20, 2024
