### ISSUE TITLE
[TASK] Update Model Usage

### ISSUE THREAD

**Issue by kunal0137** [SEMOSS/semoss#111]
### Description 

Show the how to use a model if it is an Embedding model in pixel/python in order to generate embeddings.

Additionally, show how to use the model through the OpenAI interface

### Existing

Is there any relevant code or ui feature that the developer should know about when resolving this issue. 

### Reference

This issue references. . .

### Tasks

What are more specific tasks that a developer needs to take to consider this issue resolved.

**Comment by ghost** [comment]
Assigned by Jeff. We are relatively new to the platform.
Questions about the issue:
1. What is / How would you generate an embedding?
2. Is this just an update to the Usage panel on an embedded model?
3. Could you provide examples of using models with the OpenAI interface / where that interface is?

Thanks for the help.
