### ISSUE TITLE
Unable to add new members to a model while not an admin 

### ISSUE THREAD

**Issue by ppatel9703** [SEMOSS/semoss#150]
### Description 

Adding members while not in admin mode causes the Backend to throw 500

**Comment by shivanshpatel13** [comment]
<img width="955" alt="Unable to add new members to a model while not an admin #150" src="https://github.com/user-attachments/assets/daf6ea8b-bc45-4f47-9b56-1ca6abb78f80">

Created a test user to add to model while not an admin, it works successfully in this case.

**Comment by johbaxter** [comment]
Not an issue

1. Was able to swap settings for users that are already a member

2. I am able to add members to the same status as i am.  
-  If i am owner i can add any one as author, editor, read only 
-  If i am editor i can add any one as  editor, read only 
-  If i am read only i can add any one as read only

**Comment by johbaxter** [comment]
Not an issue

Was able to swap settings for users that are already a member

I am able to add members to the same status as i am.

If i am owner i can add any one as author, editor, read only
If i am editor i can add any one as editor, read only
If i am read only i can add any one as read only
