### ISSUE TITLE
[Function] Phase 2 of Prompt Library BE

### ISSUE THREAD

**Issue by iclyn-taero** [SEMOSS/Semoss#32]
- [ ] Bookmarking functionality using additional prompt/user relation table
- [ ] Add "most popular" tracker on prompts

**Comment by ppatel9703** [comment]
Waiting for PR for phase 1 to be merge and FE component to finish

**Comment by EJV20** [comment]
Make sure to add version ids and versioning for prompts

**Comment by EJV20** [comment]
https://www.figma.com/design/90i9MKLBGrW9imf0wLWvZ0/Agent-Builder?node-id=856-72479&t=8ShlrHOPJtkuKdyd-1 

Figma link
