### ISSUE TITLE
[TASK] Ability to add metadata to sources on pgvector

### ISSUE THREAD

**Issue by themaherkhalil** [SEMOSS/semoss#36]
### Description 

Need to be able to add custom metadata with the documents being indexed or after they are indexed

### Existing

addDocument takes in a generic parameter map which should be used to pass in metadata based on the source document name

### Tasks

What are more specific tasks that a developer needs to take to consider this issue resolved.

**Comment by ppatel9703** [comment]
I would be able to take this on if I can get some more info on what the metadata would be and how we want to store it
