### ISSUE TITLE
[TASK] Update or Create New Reactors/Endpoint for PublishProject, /getUserProjectPermission and /setProjectPortal

### ISSUE THREAD

**Issue by trevorzylks** [SEMOSS/semoss#45]
### Description 

If the user is in admin mode, we want to hit admin related reactors/endpoints. Right now, these endpoints will cause issues on the FE if the user is in admin mode, but not a member of the app.  

### Tasks

Either create new reactors/endpoints, or add in params to denote that the user is in admin mode.

**Comment by ppatel9703** [comment]
@themaherkhalil Should an admin be able to publish a project? I feel like they should be able to delete but not publish. Will defer to your opinion on it though

**Comment by ppatel9703** [comment]
@trevorzylks Lets only worry about reactors that currently throw errors when displaying the page. 
If a user wants to publish or change something have them set themselves as an owner to (admins can do that already)

**Comment by trevorzylks** [comment]
@ppatel9703 If we only wanted to address the unnecessary call being made upon initially rendering the page, then we can close out this issue. 

Related issue: https://github.com/SEMOSS/semoss-ui/issues/207

**Comment by trevorzylks** [comment]
Closing this issue. Need further clarification on admin capabilities / what should be shown on the FE.
