### ISSUE TITLE
[TASK] Create DB and BE CRUD reactors for a prompt hub

### ISSUE THREAD

**Issue by johbaxter** [SEMOSS/semoss#78]
### Description 

Expand on the original issue to talk through what the purpose of the ticket is. 

### Existing

Is there any relevant code or ui feature that the developer should know about when resolving this issue. 

### Reference

This issue references. . .

### Tasks

What are more specific tasks that a developer needs to take to consider this issue resolved.

**Comment by johbaxter** [comment]
https://github.com/SEMOSS/playground/issues/44

**Comment by ppatel9703** [comment]
- AddPrompt(map=[{"context":"Translate {{question}}","title":"First","intent":"Test Prompt","tags":["World","GAMING","PLANTS"]}]);
	- ListPrompt();
	- UpdatePrompt(map=[{"context":"Updated Context {{Location}}","id":"6442bba6-f374-40b6-bf21-ff595b6fe4df","title":"Updated Test Title","intent":"Updated Test intent","tags":["World","GAMING","PLANTS"]}]);
	-CheckPromptTitle() -> checks to see if prompt title is currently used or not
